ElectronicObserverEN/ElectronicObserver

- ElectronicObserver/Data/Battle/Phase/PhaseTorpedo.cs
- ElectronicObserver/Utility/SoftwareInformation.cs
* 戦闘：連合vs連合でエラーが発生するのを修正 (#294)
> Version 4.7.1

- ElectronicObserver/App.xaml
- ElectronicObserver/ViewModels/FormMainViewModel.cs
- ElectronicObserver/Window/Wpf/InformationView/InformationView.xaml
- ElectronicObserver/Window/Wpf/InformationView/InformationView.xaml.cs
- ElectronicObserver/Window/Wpf/InformationView/InformationViewModel.cs
- ElectronicObserver/Window/Wpf/ViewTemplateSelector.cs
- ElectronicObserver/Window/Wpf/ViewTemplates.xaml
--Changed FormInformation to WPF Information
--Adjusted textbox behaviour to match winforms
> Wpf information main

- ElectronicObserver/Window/Tools/EventLockPlanner/EventLockPlannerViewModel.cs
- ElectronicObserver/Window/Wpf/Fleet/FleetViewModel.cs
- ElectronicObserver/Window/Wpf/Fleet/ViewModels/FleetItemViewModel.cs
> Use planned event tag color in fleet view

- ElectronicObserver/ViewModels/FormMainViewModel.cs
- ElectronicObserver/Window/Wpf/Log/LogView.xaml
- ElectronicObserver/Window/Wpf/Log/LogView.xaml.cs
- ElectronicObserver/Window/Wpf/Log/LogViewModel.cs
- ElectronicObserver/Window/Wpf/Log/LogViewViewModel.cs
- ElectronicObserver/Window/Wpf/ViewTemplateSelector.cs
- ElectronicObserver/Window/Wpf/ViewTemplates.xaml
--Reworked to use ListView instead of ItemsControl
--Readded scrollchanged to match the previous autoscroll behaviour
> Pr logview rework

- ElectronicObserver/Observer/kcsapi/api_req_map/next.cs
--Fix for discord RPC only showing sortie-ing to first node when sortied
> Fix for discord RPC showing only first node of a map when sortied

- ElectronicObserver/Data/Battle/BattleManager.cs
--Fix ID1 gun count in battlemanager
> Refix BattleManager for ID1 Gun counting

- ElectronicObserver/Window/Wpf/Fleet/FleetView.xaml
- ElectronicObserver/Window/Wpf/Fleet/ViewModels/ProgressBarProps.cs
- ElectronicObserver/Window/Wpf/Fleet/ViewModels/ShipResourceViewModel.cs
--added blinking background to indicate empty fuel/ammo bar
--For Issue #243
> Empty Supply Indication

- ElectronicObserver/Window/Wpf/ExpeditionCheck/ExpeditionCheckRow.cs
- ElectronicObserver/Window/Wpf/ExpeditionCheck/ExpeditionCheckView.xaml
> Add Background Color by world similar to quest view

- ElectronicObserver/Window/Tools/FleetImageGenerator/FleetImageGeneratorWindow.xaml
- ElectronicObserver/Window/Tools/FleetImageGenerator/FleetViewModel.cs
- ElectronicObserver/Window/Tools/FleetImageGenerator/TPValue.cs
- ElectronicObserverTypes/Mocks/ShipDataMock.cs
--Added TP similar to noro 
--updated mock for allslotmaster for tp calc
> Add TP for FleetImageGenerator

- ElectronicObserver/Utility/Data/EquipmentUpgradeCostExtensions.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/CostCalculation/EquipmentUpgradePlanCostConsumableViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/CostCalculation/EquipmentUpgradePlanCostEquipmentViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/CostCalculation/EquipmentUpgradePlanCostItemModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/CostCalculation/EquipmentUpgradePlanCostItemViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/CostCalculation/EquipmentUpgradePlanCostModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/CostCalculation/EquipmentUpgradePlanCostViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlanItemViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlanner.Designer.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlanner.resx
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlannerViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlannerWindow.xaml
- ElectronicObserverCoreTests/UpgradeCostTests.cs
It's not actual part 3 but something I forgot in part 2 (cost calculation)
> Equipment upgrade planner Part 2 (bonus)

- Browser/Browser.csproj
- Browser/CefSharpBrowser/CefOp/CefKeyboardHandler.cs
- Browser/CefSharpBrowser/CefSharpViewModel.cs
--change to Cefsharp HwndHost to remove stutters
> CefSharp HwndHost ver

- ElectronicObserver/Resource/Record/ResourceRecord.cs
> Adjust Senka Cutoff

- ElectronicObserver/Utility/SoftwareUpdater.cs
- ElectronicObserverCoreTests/FitBonusTest.cs
- ElectronicObserverCoreTests/Startup.cs
- ElectronicObserverCoreTests/UpgradeCostTests.cs
The goal is to automatically run unit tests on every pull request and when we push code on the main branch.
> Run unit tests with a GitHub action

- ElectronicObserver/Properties/Window/FleetResources.en.resx
- ElectronicObserver/Properties/Window/FleetResources.resx
- ElectronicObserver/Utility/Data/ActivatableEquipmentNoneModel.cs
- ElectronicObserver/Utility/Data/FleetDataExtensions.cs
- ElectronicObserver/ViewModels/Translations/FormFleetOverviewTranslationViewModel.cs
- ElectronicObserver/ViewModels/Translations/FormFleetTranslationViewModel.cs
- ElectronicObserver/Window/Wpf/Fleet/FleetView.xaml
- ElectronicObserver/Window/Wpf/Fleet/ViewModels/FleetStatusViewModel.cs
- ElectronicObserver/Window/Wpf/Fleet/ViewModels/TotalRate.cs
- ElectronicObserver/Window/Wpf/FleetOverview/CombinedFleetOverviewItemViewModel.cs
- ElectronicObserver/Window/Wpf/FleetOverview/FleetOverviewView.xaml
- ElectronicObserver/Window/Wpf/FleetOverview/FleetOverviewViewModel.cs
- ElectronicObserverCoreTests/SmokeGeneratorTests.cs
- ElectronicObserverTypes/Extensions/FleetDataExtensions.cs
- ElectronicObserverTypes/Extensions/ShipDataExtensions.cs
- ElectronicObserverTypes/IActivatableEquipment.cs
- ElectronicObserverTypes/SmokeGeneratorTriggerRate.cs
> Display smoke generator trigger rate

- ElectronicObserver/App.xaml.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlanItemViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlanItemWindow.xaml
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlanManager.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlannerViewModel.cs
- ElectronicObserver/Window/Tools/EquipmentUpgradePlanner/EquipmentUpgradePlannerWindow.xaml
- Added Scroll viewer to handle scroll
- Compact mode is now supported in the edit view
- Should fix #456
> Adjusted Equipment upgrade edit form display

- .editorconfig
- ElectronicObserver/Data/Constants.cs
- ElectronicObserver/Data/Quest/ProgressAGo.cs
- ElectronicObserver/Data/Quest/ProgressBattle.cs
- ElectronicObserver/Data/Quest/ProgressPractice.cs
- ElectronicObserver/Properties/Window/Dialog/DropRecordViewerResources.en.resx
- ElectronicObserver/Properties/Window/Dialog/DropRecordViewerResources.resx
- ElectronicObserver/ViewModels/Translations/DialogDropRecordViewerTranslationViewModel.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordContentType.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordFilterViewModel.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordRow.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordRowBase.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordViewerViewModel.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordViewerWindow.xaml
- ElectronicObserver/Window/Tools/DropRecordViewer/DropRecordViewerWindow.xaml.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/MergedDropRecordRow.cs
- ElectronicObserver/Window/Tools/DropRecordViewer/MergedRowCounter.cs
> Drop record viewer refactor

- ElectronicObserver/Data/Battle/BattleManager.cs
- ElectronicObserver/Data/Battle/BattleRankPrediction.cs
- ElectronicObserver/Data/Battle/Phase/PhaseInitial.cs
- ElectronicObserver/Data/ShipData.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/DataExport/BattleRanksExportMap.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/DataExport/BattleRanksExportModel.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/DataExport/CsvExportResources.en.resx
- ElectronicObserver/Window/Tools/SortieRecordViewer/DataExport/CsvExportResources.resx
- ElectronicObserver/Window/Tools/SortieRecordViewer/DataExport/DataExportHelper.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/Sortie/Battle/Phase/PhaseAirBattleBase.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/Sortie/Battle/Phase/PhaseInitial.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/Sortie/Battle/Phase/PhaseTorpedo.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/SortieRecordViewerViewModel.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/SortieRecordViewerWindow.xaml
- ElectronicObserverCoreTests/BattleRank/BattleRankTest01.json
- ElectronicObserverCoreTests/BattleRank/BattleRankTest02.json
- ElectronicObserverCoreTests/BattleRank/BattleRankTest03.json
- ElectronicObserverCoreTests/BattleRank/BattleRankTest04.json
- ElectronicObserverCoreTests/BattleRank/BattleRankTest05.json
- ElectronicObserverCoreTests/BattleRank/BattleRankTests.cs
- ElectronicObserverCoreTests/ElectronicObserverCoreTests.csproj
- ElectronicObserverTypes/IShipData.cs
- ElectronicObserverTypes/Mocks/ShipDataMock.cs
- To find the issue, we'll need an export of expected vs actual battle ranks
- We need to have the rank prediction code to be testable
- Then fix the issues like the one in #447
> Try to improve and fix Battle Rank Prediciton Issues

- ElectronicObserver.KancolleApi.Types/ApiReqQuest/Clearitemget/APIReqQuestClearitemgetResponse.cs
- ElectronicObserver/App.xaml.cs
- ElectronicObserver/Database/ElectronicObserverContext.cs
- ElectronicObserver/ElectronicObserver.csproj
- ElectronicObserver/Window/Tools/ExpeditionRecordViewer/ExpeditionRecordViewerViewModel.cs
- ElectronicObserver/Window/Tools/SenkaViewer/SenkaViewerTranslationViewModel.cs
- ElectronicObserver/Window/Tools/SenkaViewer/SenkaViewerViewModel.cs
- ElectronicObserver/Window/Tools/SenkaViewer/SenkaViewerWindow.xaml
- ElectronicObserver/Window/Tools/SortieRecordViewer/Extensions.cs
- ElectronicObserver/Window/Tools/SortieRecordViewer/SortieRecordViewerViewModel.cs
The main performance issue seems to come from the SQL data reader, I don't feel like dealing with that right now.
> Database performance improvement

- Browser/Properties/Resources.zh-CN.resx
- Browser/WebView2Browser/AirControlSimulator/AirControlSimulatorResources.zh-CN.resx
- Browser/WebView2Browser/CompassPrediction/CompassPredictionResources.zh-CN.resx
Kamikaze-chan:
I will try to submit Chinese translations regularly. It is almost the time for the Chinese festival "Spring Festival" (equivalent to Christmas in the United States and Japan), so my progress will be a little slower than before.
> Chinese version

- ElectronicObserver/ElectronicObserver.csproj
- ElectronicObserver/Notifier/NotifierBase.cs
- ElectronicObserver/Utility/EOMediaPlayer.cs
- ElectronicObserver/Utility/SyncBGMPlayer.cs
- ElectronicObserver/ViewModels/FormMainViewModel.cs
The main goal is making EO remember the system volume settings (the volume mixer value).
The WPF media player was ignoring the system volume for some reason, so I had to replace it with NAudio.
Note: when syncing mute with browser, all sounds including notifications will get muted when you mute the browser.
> media player rework

- ElectronicObserver/Data/DiscordRPC/DiscordRpcManager.cs
- ElectronicObserver/Data/DiscordRPC/RpcIconKind.cs
- ElectronicObserver/Observer/kcsapi/api_port/port.cs
- ElectronicObserver/Properties/Window/Dialog/ConfigurationResources.en.resx
- ElectronicObserver/Properties/Window/Dialog/ConfigurationResources.resx
- ElectronicObserver/Properties/Window/Dialog/ConfigurationResources.zh-CN.resx
- ElectronicObserver/Utility/Configuration.cs
- ElectronicObserver/Window/Settings/Behavior/ConfigurationBehaviorTranslationViewModel.cs
- ElectronicObserver/Window/Settings/Behavior/ConfigurationBehaviorUserControl.xaml
- ElectronicObserver/Window/Settings/Behavior/ConfigurationBehaviorViewModel.cs
- ElectronicObserver/Window/Settings/Behavior/ConfigurationBehaviorViewModelProxy.cs
~~We need new tl for Control_DiscordRPCMessageToolTip~~
> Allow user to choose the ship to use for Discord Rich Presence

- ElectronicObserver.Avalonia/Program.cs
This is a countermeasure to Issues #535.
> Change CompositionMode to RedirectionSurface.(Issues #535)

- README.md
- README_CN.md
- Readme_ES.md
> Readme created for ES and updated to previous Readmes 

- ElectronicObserver.Core/Services/IClipboardService.cs
- ElectronicObserver/App.xaml.cs
- ElectronicObserver/LoggerRes.en.resx
- ElectronicObserver/LoggerRes.resx
- ElectronicObserver/Services/ToolService.cs
- ElectronicObserver/Utility/ClipboardExtensions.cs
- ElectronicObserver/Utility/ClipboardService.cs
- ElectronicObserver/Window/Dialog/DialogShipGroupFilter.cs
- ElectronicObserver/Window/Tools/AirControlSimulator/AirControlSimulatorViewModel.cs
- ElectronicObserver/Window/Wpf/Quest/QuestViewModel.cs
- ElectronicObserverCoreTests/BattleRank/BattleRankTests.cs
- ElectronicObserverCoreTests/CsvExport/CsvExportTests.cs
- ElectronicObserverCoreTests/SortieCost/SortieCostTestBase.cs
- ElectronicObserverCoreTests/SortieDetail/SortieDetailTests.cs
- ElectronicObserverCoreTests/Startup.cs
Related to #544.
It won't fix it, but it will prevent EO from crashing and add some log.
> Copying to clipboard shouldn't crash EO
